version: "3"

services:
  db:
    image:
    networks: [ back ]

  backend:
    build:
    networks: [ back, front ]

  frontend:
    build:
    networks: [ front ]

networks:
  back:
    driver: "bridge"
  front:
    driver: "bridge"
