name: Backend lint and tests

run-name: ${{ github.event_name }} to ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    paths:
      - prostoyoga/backend/**
  pull_request:
    paths:
      - prostoyoga/backend/**

env:
  path: ./prostoyoga/backend

jobs:
  linting_black:
    name: Black lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]
    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Set up Python (${{ matrix.python-version }})
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run black
        uses: psf/black@stable
        with:
          options: "--check --verbose --diff --color"
          src: "${{ env.path }}"
          version: "24.2.0"

  linting_flake:
    name: Flake8 lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]
    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Set up Python (${{ matrix.python-version }})
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          args: "show-source statistics"
          max-line-length: 88
          path: "${{ env.path }}"
          plugins: "flake8-bugbear"
