name: Linting with flake8

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      source_path:
        required: true
        type: string
      max-line-length:
        required: false
        default: 88
        type: number

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get backend code
        uses: actions/checkout@v4
        with:
          show-progress: true
          sparse-checkout: ${{ inputs.source_path }}
          sparse-checkout-cone-mode: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install flake8 and plugins
        run: pip install flake8 flake8-bugbear

      - name: Flake8 linting
        run: |
          flake8 --statistics --show-source \
          --max-line-length ${{ inputs.max-line-length }} \
          ${{ inputs.source_path }}